### ISSUE TITLE
*combat listing characters in terms of entry order instead of init order

### ISSUE THREAD

**Issue by skelegorg** [skelegorg/dnd-discord-bot#15]

**Comment by realPolyhedral** [comment]
@skelegorg can you create a pull request for the newest working ver. with the json stuff pls

**Comment by realPolyhedral** [comment]
so i can fix these issues

**Comment by skelegorg** [comment]
@realPolyhedral i will shortly

**Comment by skelegorg** [comment]
@realPolyhedral, I am merging JSON integration into master - create a pull request from Master in just a moment

**Comment by skelegorg** [comment]
fixed in next commit
